# Generated by Django 5.0.7 on 2024-07-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_item_unique_identifier_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_identifier',
        ),
    ]
